apps/atencion/urls.py
from django.conf.urls import url
from django.conf.urls import patterns, include, url
from apps.atencion.views import DiagnosticoBuscar
from .views import PersonaListView, PersonaCreateView, PersonaUpdateView, PersonaDeleteView
from .views import ProductoListView, ProductoCreateView, ProductoDeleteView, ProductoUpdateView
from .views import LaboratorioListView, LaboratorioCreateView, LaboratorioDeleteView, LaboratorioUpdateView
from .views import FuncionesVitalesListView, FuncionesVitalesCreateView, FuncionesVitalesDeleteView, FuncionesVitalesUpdateView
from .views import PeriodoListView, PeriodoCreateView, PeriodoDeleteView, PeriodoUpdateView
from .views import DiagnosticoListView, DiagnosticoDeleteView, DiagnosticoUpdateView, DiagnosticoCreateView, DiagnosticoConsultaCreate
from .views import UnidadMedidaCreateView, UnidadMedidaListView, UnidadMedidaUpdateView, UnidadMedidaDeleteView
from .views import (PersonaListView, PersonaCreateView, PersonaUpdateView, PersonaDeleteView, ProductoListView, ProductoCreateView, ProductoDeleteView, ProductoUpdateView,
    ProvinciaAjax, DistritoAjax, HitoriaDetailView, AntecedenteCreateView, DiagnosticoConsultaCreate, ProductoBuscarAjaxView)
from .views import HitoriaBusquedaTemplateView, HitoriaCreateView, vista, BarView

urlpatterns = [

    url(r'^historia/busqueda$', HitoriaBusquedaTemplateView.as_view(), name="historia_search"),
    url(r'^historia/crear$', HitoriaCreateView.as_view(), name="historia_add"),
    url(r'^historia/detalle/(?P<pk>\d+)$', HitoriaDetailView.as_view(), name="historia_detail"),

    # persona
    url(r'^persona/lista$', PersonaListView.as_view(), name="persona_list"),
    url(r'^persona/crear/$', PersonaCreateView.as_view(), name="persona_add"),
    url(r'^persona/eliminar/(?P<pk>\d+)$', PersonaDeleteView.as_view(), name="persona_delete"),
    url(r'^persona/editar/(?P<pk>\d+)$', PersonaUpdateView.as_view(), name="persona_update"),
    url(r'^distrito_ajax/$', DistritoAjax.as_view(), name='busqueda_distrito'),
    url(r'^provincia_ajax/$', ProvinciaAjax.as_view(), name='busqueda_provincia'),

    # Producto
    url(r'^producto/lista$', ProductoListView.as_view(), name="producto_list"),
    url(r'^producto/crear/$', ProductoCreateView.as_view(), name="producto_add"),
    url(r'^producto/eliminar/(?P<pk>\d+)$', ProductoDeleteView.as_view(), name="producto_delete"),
    url(r'^producto/editar/(?P<pk>\d+)$', ProductoUpdateView.as_view(), name="producto_update"),
    url(r'^producto/buscar/$', ProductoBuscarAjaxView.as_view(), name="medicamento_search"),
    # Laboratorio
    url(r'^laboratorio/lista$', LaboratorioListView.as_view(), name="laboratorio_list"),
    url(r'^laboratorio/crear/$', LaboratorioCreateView.as_view(), name="laboratorio_add"),
    url(r'^laboratorio/eliminar/(?P<pk>\d+)$', LaboratorioDeleteView.as_view(), name="laboratorio_delete"),
    url(r'^laboratorio/editar/(?P<pk>\d+)$', LaboratorioUpdateView.as_view(), name="laboratorio_update"),


    # FuncionesVitales
    url(r'^funcionesvitales/lista$', FuncionesVitalesListView.as_view(), name="funcionesvitales_list"),
    url(r'^funcionesvitales/crear/$', FuncionesVitalesCreateView.as_view(), name="funcionesvitales_add"),
    url(r'^funcionesvitales/eliminar/(?P<pk>\d+)$', FuncionesVitalesDeleteView.as_view(), name="funcionesvitales_delete"),
    url(r'^funcionesvitales/editar/(?P<pk>\d+)$', FuncionesVitalesUpdateView.as_view(), name="funcionesvitales_update"),

    # Periodo
    url(r'^periodo/lista$', PeriodoListView.as_view(), name="periodo_list"),
    url(r'^periodo/crear/$', PeriodoCreateView.as_view(), name="periodo_add"),
    url(r'^periodo/eliminar/(?P<pk>\d+)$', PeriodoDeleteView.as_view(), name="periodo_delete"),
    url(r'^periodo/editar/(?P<pk>\d+)$', PeriodoUpdateView.as_view(), name="periodo_update"),

    # Diagnostico
    url(r'^diagnostico/lista$', DiagnosticoListView.as_view(), name="diagnostico_list"),
    url(r'^diagnostico/crear/$', DiagnosticoConsultaCreate.as_view(), name="diagnostico_add"),
    url(r'^diagnostico/nuevo/$', DiagnosticoCreateView.as_view(), name="diagnostico_create"),
    url(r'^diagnostico/eliminar/(?P<pk>\d+)$', DiagnosticoDeleteView.as_view(), name="diagnostico_delete"),
    url(r'^diagnostico/editar/(?P<pk>\d+)$', DiagnosticoUpdateView.as_view(), name="diagnostico_update"),
    url(r'^diagnostico/buscarajax$', DiagnosticoBuscar.as_view(), name="diagnostico_search"),

    # UnidadMedida
    url(r'^unidadmedida/lista$', UnidadMedidaListView.as_view(), name="unidadmedida_list"),
    url(r'^unidadmedida/crear/$', UnidadMedidaCreateView.as_view(), name="unidadmedida_add"),
    url(r'^unidadmedida/eliminar/(?P<pk>\d+)$', UnidadMedidaDeleteView.as_view(), name="unidadmedida_delete"),
    url(r'^unidadmedida/editar/(?P<pk>\d+)$', UnidadMedidaUpdateView.as_view(), name="unidadmedida_update"),

    # Antecedentes
    url(r'^antecedente/crear/$', AntecedenteCreateView.as_view(), name="antecedente_add"),

    #Reportes
    url(r'^reporte/atencion/$', vista, name="reporte_atencion"),
    url(r'^barbash/$', BarView.as_view(), name="bar"),

   



]

apps/mod_backend/urls.py
from django.conf.urls import url
from django.views.generic.base import TemplateView
from apps.mod_backend.views import dashboard

urlpatterns = [

    # url(r'^dashboard/$', TemplateView.as_view(template_name="mod_backend/base_mod_backend.html"), name='dashboard'),
    url(r'^dashboard/', dashboard, name='dashboard'),

]

demo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from apps.home import views as home_views
from django import views as django_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^home/', include('apps.home.urls', namespace='home')),
    url(r'^$', home_views.index, name='index'),

    url(r'^space/', include('apps.space.urls', namespace='space')),
    url(r'^sad/', include('apps.sad.urls', namespace='sad')),

    url(r'^mod_backend/',
        include('apps.mod_backend.urls', namespace='mod_backend')),

    url(r'^accounts/', include('apps.accounts.urls')),


    # http://stackoverflow.com/questions/19625102/django-javascript-translation-not-working
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/', django_views.i18n.javascript_catalog),

    # atencion

    
    url(r'^atencion/', include('apps.atencion.urls', namespace="atencion")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# https://docs.djangoproject.com/en/1.6/ref/views/
# https://docs.djangoproject.com/en/1.6/howto/static-files/
"""
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT,
        'show_indexes': settings.DEBUG
    }),
"""

apps/mod_backend/models.py
from django.db import models

# Create your models here.

apps/mod_backend/views.py
from django.views.generic.base import TemplateView
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib import messages
from apps.utils.decorators import permission_resource_required

# Create your views here.

#@permission_resource_required
def dashboard(request):
    """
    """

    c = {
        'cmi' : 'mod_backend:dashboard',
        'opts': _('Home'),
        'title': _('Backend Home Page.'),
    }
    return render(request, 'mod_backend/base_mod_backend.html', c)

apps/mod_backend/templates/mod_backend/partials/aside.html
{% block aside %}
    <div>
                    <h2>Menu</h2>
                    <ul class="side-nav nav nav-second-level col-xs-2 col-md-2">
                        <li>
                            <a href="{% url 'atencion:persona_list' %}"><h4>Pacientes</h4></a>
                        </li>
                        <li>
                            <a href="{% url 'atencion:historia_busqueda' %}"><h4>Buscar Paciente</h4></a>
                        </li>
                        <li>
                            <a href="{% url 'atencion:historia_busqueda' %}"><h4>Buscar Paciente</h4></a>
                        </li>
                        <li>
                            <a href="{% url 'atencion:producto_list' %}"><h4>Medicamentos</h4></a>
                        </li>
                        <li>
                            <a href="{% url 'atencion:periodo_list' %}"><h4>Periodo</h4></a>
                        </li>
                        <li>
                            <a href="{% url 'atencion:laboratorio_list' %}"><h4>Prueba de Laboratorio</h4></a>
                        </li>
                        <li>
                            <a href="{% url 'atencion:funcionesvitales_list' %}"><h4>Funciones Vitales</h4></a>
                        </li>
                        <li>
                            <a href="{% url 'atencion:unidadmedida_list' %}"><h4>Unidad de Medida</h4></a>
                        </li>
                        <li>
                            <a href="{% url 'atencion:diagnostico_list' %}"><h4>CIE10</h4></a>
                        </li>
                        <li>
                            <a hhref="{% url 'atencion:diagnostico_list' %}"><h4>CIE10</h4></a>
                        </li>
                    </ul>
                </div>
{% endblock aside %}

apps/mod_backend/templates/mod_backend/partials/footer - copia.html
{% load i18n staticfiles %}

<footer class="navbar navbar-inverse navbar-fixed-bottom hidden-xs">
	<div class="container">
		<div class="pull-right hidden-xs">
			<p>Versión: 1.0b2 Power by <a href="http://djangoproject.com/"  target="_blank" >Django</a> |
				<a href="http://www.dailyscript.com.co/contacto/"  target="_blank" >DS</a>
			</p>
		</div>
		<div>
			<p>Backend &copy; {% now "Y" %} <a href="#"  target="_blank">Submit Consulting</a>. Todos los derechos reservados. 
			</p>
		</div>
	</div>
</footer>

<footer class="navbar navbar-inverse navbar-fixed-bottom hidden-xs">
    <div class="container">
        <div class="pull-right hidden-xs">
            <p>Versión: 1.0b2 - Ip: 127.0.0.1 - Tiempo: 0.1849 seg.</p>            
        </div>
        <div>
            <p class="visible-xs">&copy; Copyright 2014.</p>
            <p class="visible-xs">Todos los derechos reservados.</p>
            <p class="hidden-xs">&copy; Copyright 2014. Todos los derechos reservados.</p>
        </div>                
    </div>        
</footer>

apps/mod_backend/templates/mod_backend/partials/footer.html
{% load i18n staticfiles %}

<footer class="navbar navbar-inverse navbar-fixed-bottom hidden-xs">
    <div class="container">
        <div class="pull-right hidden-xs">
            <p>Versión: 1.0b2 Power by <a href="http://djangoproject.com/"  target="_blank" >Django</a> |
				<a href="http://www.dailyscript.com.co/contacto/"  target="_blank" >DS</a>
			</p>          
        </div>
        <div>
            <p class="visible-xs">&copy; Copyright x{% now 'Y' %}.</p>
            <p class="visible-xs">Todos los derechos reservados.x</p>
            <p class="hidden-xs">Backengo &copy; {% now 'Y' %} <a href="#"  target="_blank">Submit Consulting</a>. Todos los derechos reservados.</p>
        </div>                
    </div>        
</footer>

apps/mod_backend/templates/mod_backend/partials/header - copia.html
{% load staticfiles %}
{% load i18n %}
<!-- Fixed navbar -->
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Project name</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li class="dropdown-header">Nav header</li>
              <li><a href="#">Separated link</a></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="../navbar/">Default</a></li>
          <li><a href="../navbar-static-top/">Static top</a></li>
          <li class="active"><a href="./">Fixed top</a></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>

apps/mod_backend/templates/mod_backend/partials/header.html
{% load i18n user_menu %}
<!-- Fixed navbar inverse default -->
<style>
  a:hover{
    color:#fff;
  }

</style>
<div class="navbar navbar-inverse navbar-fixed-top menu-top">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="offcanvas" data-target=".navbar-offcanvas" data-canvas="body">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class='navbar-brand'>
    <ul class="navbar-brand2">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle title" data-toggle="dropdown"><i class="fa fa-cloud fa-lg"></i> {% get_info request %} <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><a href="#">Grupo 1</a></li>
          <li><a href="#">Grupo 2</a></li>
          <li class="divider"></li>
          <li><a href="/accounts/">Elegir sede</a></li>
        </ul>
      </li>
    </ul>
    </div>

  </div>
  <div class="navbar-offcanvas offcanvas">


    <div class="navmenu-brand">
      <a href="/space/solution/create/" class="btn btn-primary" title="{% trans "Log in" %}"><i class="glyphicon glyphicon-log-in"></i> <span>{% trans 'Log in'|truncatechars:10  %}</span>
      </a>
      <a href="/space/solution/create/" class="btn btn-info" title="{% trans "Add" %} {% trans "user" %}"><i class="fa fa-plus fa-lg"></i> <span>{% trans 'Sign up'|truncatechars:9 %}</span>
      </a>
    </div>
    
    <form class="navbar-form navbar-left form-controlx" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
      </form>
   
    
    {% view_menu request %}
    <!--
    <ul class="nav navbar-nav">
      <li class="divider visible-xs"></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Space <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu" >
          <li class="divider visible-xs"></li>
          <li {% ifequal cmi 'solution' %} class="active" {% endifequal %}>
            <a href="/space/solution/index/">Solution</a>
          </li>
        </ul>
      </li>

      <li class="divider visible-xs"></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">SAD <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu" >
          <li class="divider visible-xs"></li>
          <li {% ifequal cmi 'permission' %} class="active" {% endifequal %}>
            <a href="/sad/permission/index/">permission</a>
          </li>

          <li class="divider visible-xs"></li>
          <li {% ifequal cmi 'group' %} class="active" {% endifequal %}>
            <a href="/sad/group/index/">group</a>
          </li>
          
          <li class="divider visible-xs"></li>
          <li {% ifequal cmi 'grouppermissions' %} class="active" {% endifequal %}>
            <a href="/sad/grouppermissions/update/">group permissions</a>
          </li>

          <li class="divider visible-xs"></li>
          <li {% ifequal cmi 'module' %} class="active" {% endifequal %}>
            <a href="/sad/module/index/">module</a>
          </li>

          <li class="divider visible-xs"></li>
          <li {% ifequal cmi 'modulesolutions' %} class="active" {% endifequal %}>
            <a href="/sad/modulesolutions/update/">module solution</a>
          </li>

          <li class="divider visible-xs"></li>
          <li {% ifequal cmi 'menu' %} class="active" {% endifequal %}>
            <a href="/sad/menu/index/">menu</a>
          </li>
          
        </ul>
      </li>
    </ul>
    -->
    
    
    
    
    <ul class="nav navbar-nav navbar-right hidden-xs">
      <li class="divider visible-xs"></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color:#000;"><i class="fa fa-user"></i> {{user}}<span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li class="divider visible-xs"></li>
          <li><a href="#">Actionx</a></li>
          <li class="divider visible-xs"></li>
          <li><a href="#">Another action</a></li>
          <li class="divider visible-xs"></li>
          <li><a href="/accounts/password/change/">{% trans 'Change password' %}</a></li>
          <li class="divide visible-xs"></li>
          <li class="divider"></li>
          <li><a href="/accounts/logout/">Salir</a></li>
        </ul>
      </li>
    </ul>

    <ul class="nav navbar-nav visible-xs">

      <li class="divider"></li>
      <li><a href="/dbkm/sistema/mi_cuenta/" >Mi Cuenta {{user}} </a></li>

      <li class="divider"></li>
      <li><a href="/accounts/logout/"  class="no-load" ><i class="fa fa-pd-expand fa-power-off"></i> {% trans 'Log out' %}</a></li>

      <li class="divider"></li>
      <li>
        <div class="text-center">
          <p style="color: #ccc"><i class="fa fa-tint fa-lg"></i> Backengo &copy; {% now 'Y' %}, asullom.</p>
          <p style="color: #ccc">{% trans 'All rights reserved.' %}</p>

        </div>
      </li>
    </ul>

  </div><!--/.nav-collapse -->
</div>


<script type="text/javascript">
$(document).ready(function() {
  //url = (window.location.hash.lenth >1) ? window.hash : window.location.pathname;

  //url = url.split('create')[0].split('update')[0];



  $(".dropdown-menu li").each(function(i) {
    //$(this).find('li').each(function(i){
     //if(url==$(this).attr('href')) {
      //alert($(this).attr('class'));
      if( $(this).attr('class')==('active') ) {
      $(this).parent().parent().addClass('active ');//open
      return false;
    }

  //});
});

});
/** Tooltip **/
$(function() { $("[rel=tooltip]").tooltip(); });
</script>              

apps/mod_backend/templates/mod_backend/partials/main.html
{% load staticfiles %}
{% load i18n %}
{% load user_menu %}
<div class="main-nav-wrapper hidden-phone hidden-tablet">
    <div class="navbar navbar-fixed-top main-nav">
        <div class="navbar-inner">
            <div class="container-fluid ">                        
                <div class="nav-collapse">
                    {% desktop request %}
                </div>
            </div>                    
        </div>
    </div> 
    {% desktop_items request %}
</div>