apps/atencion/urls.py
from django.conf.urls import url
from django.conf.urls import patterns, include, url
from apps.atencion.views import DiagnosticoBuscar
from .views import PersonaListView, PersonaCreateView, PersonaUpdateView, PersonaDeleteView
from .views import ProductoListView, ProductoCreateView, ProductoDeleteView, ProductoUpdateView
from .views import LaboratorioListView, LaboratorioCreateView, LaboratorioDeleteView, LaboratorioUpdateView
from .views import FuncionesVitalesListView, FuncionesVitalesCreateView, FuncionesVitalesDeleteView, FuncionesVitalesUpdateView
from .views import PeriodoListView, PeriodoCreateView, PeriodoDeleteView, PeriodoUpdateView
from .views import DiagnosticoListView, DiagnosticoDeleteView, DiagnosticoUpdateView, DiagnosticoCreateView, DiagnosticoConsultaCreate
from .views import UnidadMedidaCreateView, UnidadMedidaListView, UnidadMedidaUpdateView, UnidadMedidaDeleteView
from .views import (PersonaListView, PersonaCreateView, PersonaUpdateView, PersonaDeleteView, ProductoListView, ProductoCreateView, ProductoDeleteView, ProductoUpdateView,
    ProvinciaAjax, DistritoAjax, HitoriaDetailView, AntecedenteCreateView, DiagnosticoConsultaCreate, ProductoBuscarAjaxView)
from .views import HitoriaBusquedaTemplateView, HitoriaCreateView, vista, BarView

urlpatterns = [

    url(r'^historia/busqueda$', HitoriaBusquedaTemplateView.as_view(), name="historia_search"),
    url(r'^historia/crear$', HitoriaCreateView.as_view(), name="historia_add"),
    url(r'^historia/detalle/(?P<pk>\d+)$', HitoriaDetailView.as_view(), name="historia_detail"),

    # persona
    url(r'^persona/lista$', PersonaListView.as_view(), name="persona_list"),
    url(r'^persona/crear/$', PersonaCreateView.as_view(), name="persona_add"),
    url(r'^persona/eliminar/(?P<pk>\d+)$', PersonaDeleteView.as_view(), name="persona_delete"),
    url(r'^persona/editar/(?P<pk>\d+)$', PersonaUpdateView.as_view(), name="persona_update"),
    url(r'^distrito_ajax/$', DistritoAjax.as_view(), name='busqueda_distrito'),
    url(r'^provincia_ajax/$', ProvinciaAjax.as_view(), name='busqueda_provincia'),

    # Producto
    url(r'^producto/lista$', ProductoListView.as_view(), name="producto_list"),
    url(r'^producto/crear/$', ProductoCreateView.as_view(), name="producto_add"),
    url(r'^producto/eliminar/(?P<pk>\d+)$', ProductoDeleteView.as_view(), name="producto_delete"),
    url(r'^producto/editar/(?P<pk>\d+)$', ProductoUpdateView.as_view(), name="producto_update"),
    url(r'^producto/buscar/$', ProductoBuscarAjaxView.as_view(), name="medicamento_search"),
    # Laboratorio
    url(r'^laboratorio/lista$', LaboratorioListView.as_view(), name="laboratorio_list"),
    url(r'^laboratorio/crear/$', LaboratorioCreateView.as_view(), name="laboratorio_add"),
    url(r'^laboratorio/eliminar/(?P<pk>\d+)$', LaboratorioDeleteView.as_view(), name="laboratorio_delete"),
    url(r'^laboratorio/editar/(?P<pk>\d+)$', LaboratorioUpdateView.as_view(), name="laboratorio_update"),


    # FuncionesVitales
    url(r'^funcionesvitales/lista$', FuncionesVitalesListView.as_view(), name="funcionesvitales_list"),
    url(r'^funcionesvitales/crear/$', FuncionesVitalesCreateView.as_view(), name="funcionesvitales_add"),
    url(r'^funcionesvitales/eliminar/(?P<pk>\d+)$', FuncionesVitalesDeleteView.as_view(), name="funcionesvitales_delete"),
    url(r'^funcionesvitales/editar/(?P<pk>\d+)$', FuncionesVitalesUpdateView.as_view(), name="funcionesvitales_update"),

    # Periodo
    url(r'^periodo/lista$', PeriodoListView.as_view(), name="periodo_list"),
    url(r'^periodo/crear/$', PeriodoCreateView.as_view(), name="periodo_add"),
    url(r'^periodo/eliminar/(?P<pk>\d+)$', PeriodoDeleteView.as_view(), name="periodo_delete"),
    url(r'^periodo/editar/(?P<pk>\d+)$', PeriodoUpdateView.as_view(), name="periodo_update"),

    # Diagnostico
    url(r'^diagnostico/lista$', DiagnosticoListView.as_view(), name="diagnostico_list"),
    url(r'^diagnostico/crear/$', DiagnosticoConsultaCreate.as_view(), name="diagnostico_add"),
    url(r'^diagnostico/nuevo/$', DiagnosticoCreateView.as_view(), name="diagnostico_create"),
    url(r'^diagnostico/eliminar/(?P<pk>\d+)$', DiagnosticoDeleteView.as_view(), name="diagnostico_delete"),
    url(r'^diagnostico/editar/(?P<pk>\d+)$', DiagnosticoUpdateView.as_view(), name="diagnostico_update"),
    url(r'^diagnostico/buscarajax$', DiagnosticoBuscar.as_view(), name="diagnostico_search"),

    # UnidadMedida
    url(r'^unidadmedida/lista$', UnidadMedidaListView.as_view(), name="unidadmedida_list"),
    url(r'^unidadmedida/crear/$', UnidadMedidaCreateView.as_view(), name="unidadmedida_add"),
    url(r'^unidadmedida/eliminar/(?P<pk>\d+)$', UnidadMedidaDeleteView.as_view(), name="unidadmedida_delete"),
    url(r'^unidadmedida/editar/(?P<pk>\d+)$', UnidadMedidaUpdateView.as_view(), name="unidadmedida_update"),

    # Antecedentes
    url(r'^antecedente/crear/$', AntecedenteCreateView.as_view(), name="antecedente_add"),

    #Reportes
    url(r'^reporte/atencion/$', vista, name="reporte_atencion"),
    url(r'^barbash/$', BarView.as_view(), name="bar"),

   



]

demo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from apps.home import views as home_views
from django import views as django_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^home/', include('apps.home.urls', namespace='home')),
    url(r'^$', home_views.index, name='index'),

    url(r'^space/', include('apps.space.urls', namespace='space')),
    url(r'^sad/', include('apps.sad.urls', namespace='sad')),

    url(r'^mod_backend/',
        include('apps.mod_backend.urls', namespace='mod_backend')),

    url(r'^accounts/', include('apps.accounts.urls')),


    # http://stackoverflow.com/questions/19625102/django-javascript-translation-not-working
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/', django_views.i18n.javascript_catalog),

    # atencion

    
    url(r'^atencion/', include('apps.atencion.urls', namespace="atencion")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# https://docs.djangoproject.com/en/1.6/ref/views/
# https://docs.djangoproject.com/en/1.6/howto/static-files/
"""
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT,
        'show_indexes': settings.DEBUG
    }),
"""

apps/atencion/forms/ConsultaEmergenciaForm.py
from django import forms
from ..models import ConsultaEmergencia


class ConsultaEmergenciaForm(forms.ModelForm):
    """Class ConsultaEmergenciaForm."""
    class Meta:
        model = ConsultaEmergencia
        exclude = ('',)
        widgets = {
            'historia': forms.Select(attrs={'class': 'form-control', 'required':'true'})
        }

apps/atencion/forms/DiagnosticoForm.py
from django import forms
from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Field, Div, Row, HTML
from crispy_forms.bootstrap import FormActions, TabHolder, Tab
from ..models import Diagnostico
from django.utils.translation import ugettext_lazy as _
from apps.utils.forms import smtSave, btnCancel, btnReset
from django.utils.text import capfirst, get_text_list
from unicodedata import normalize



class DiagnosticoForm(forms.ModelForm):
    """Class DiagnosticoForm."""
    class Meta:
        model = Diagnostico
        exclude = ('',)
        widgets = {
            'codigo': forms.TextInput(attrs={'class': 'form-control', 'required':'true', 'placeholder': 'Ingrese codigo'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'required':'true', 'placeholder': 'Ingrese nombre'}),
}

apps/atencion/templates/periodo/views.py
import logging
log = logging.getLogger(__name__)
from apps.utils.security import SecurityKey, log_params, UserToken, get_dep_objects
from django import http
from django.conf.locale import da
from django.core.urlresolvers import reverse, reverse_lazy
from django.db import transaction
from django.shortcuts import render, render_to_response, redirect
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.core import serializers
from django.http import HttpResponse, request
from django.db.models import Max, Sum
from django.contrib import messages
from django.shortcuts import get_list_or_404, get_object_or_404
from datetime import datetime, time, date
from django.contrib.auth import authenticate, login, logout
from django.db.models import Sum
from django.utils.encoding import force_text
from django.contrib.messages.views import SuccessMessageMixin
from apps.utils.decorators import permission_resource_required
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext as _ 
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from apps.utils.forms import empty
import json
from django.utils.text import capfirst, get_text_list
from .forms.PersonaForm import PersonaForm
from .forms.LaboratorioForm import LaboratorioForm
from .forms.ProductoForm import ProductoForm
from .forms.FuncionesVitalesForm import FuncionesVitalesForm

from .models import (Persona, Producto, Laboratorio, FuncionesVitales)


# class Persona==============================================================================
class PersonaListView(ListView):
    model = Persona
    template_name = 'persona/persona_list.html'
    paginate_by = settings.PER_PAGE

    @method_decorator(permission_resource_required)
    def dispatch(self, request, *args, **kwargs):
        return super(PersonaListView, self).dispatch(request, *args, **kwargs)

    def get_paginate_by(self, queryset):
        if 'all' in self.request.GET:
            return None
        return ListView.get_paginate_by(self, queryset)

    def get_queryset(self):
        self.o = empty(self.request, 'o', '-id')
        self.f = empty(self.request, 'f', 'nombres')
        self.q = empty(self.request, 'q', '')
        column_contains = u'%s__%s' % (self.f, 'contains')

        return self.model.objects.filter(**{column_contains: self.q}).order_by(self.o)


    def get_context_data(self, **kwargs):
        context = super(PersonaListView, self).get_context_data(**kwargs)
        context['opts'] = self.model._meta
        context['cmi'] = 'persona'
        context['title'] = _('Select %s to change') % capfirst(_('Persona'))

        context['o'] = self.o
        context['f'] = self.f
        context['q'] = self.q.replace('/', '-')

        return context


class PersonaCreateView(CreateView):
    model = Persona
    form_class = PersonaForm
    template_name = 'persona/persona_add.html'
    success_url = reverse_lazy('atencion:persona_list')

    @method_decorator(permission_resource_required )
    def dispatch(self, request, *args, **kwargs):
        return super(PersonaCreateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(PersonaCreateView, self).get_context_data(**kwargs)
        context['opts'] = self.model._meta
        context['cmi'] = 'persona'
        context['title'] = ('Agregar %s') % ('Persona')
        return context


    def form_valid(self, form):
        self.object = form.save(commit=False)
        
        self.object.usuario = self.request.user

        
        msg = _(' %(name)s "%(obj)s" fue creado satisfactoriamente.') % {
            'name': capfirst(force_text(self.model._meta.verbose_name)),
            'obj': force_text(self.object)
        }
        if self.object.id:
            messages.success(self.request, msg)
            log.warning(msg, extra=log_params(self.request))
        return super(PersonaCreateView, self).form_valid(form)



class PersonaUpdateView(UpdateView):
    model = Persona
    template_name = 'persona/persona_add.html'
    form_class = PersonaForm
    success_url = reverse_lazy('atencion:persona_list')

    @method_decorator(permission_resource_required )
    def dispatch(self, request, *args, **kwargs):
        return super(PersonaUpdateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(PersonaUpdateView, self).get_context_data(**kwargs)
        context['opts'] = self.model._meta
        context['cmi'] = 'persona'
        context['title'] = _('Add %s') % _('Persona')
        return context


    def form_valid(self, form):
        self.object = form.save(commit=False)

        self.object.usuario = self.request.user


        msg = _('%(name)s "%(obj)s" fue cambiado satisfactoriamente.') % {
            'name': capfirst(force_text(self.model._meta.verbose_name)),
            'obj': force_text(self.object)
        }
        if self.object.id:
            messages.success(self.request, msg)
            log.warning(msg, extra=log_params(self.request))
        return super(PersonaUpdateView, self).form_valid(form)


class PersonaDeleteView(DeleteView):
    model = Persona
    success_url = reverse_lazy('atencion:persona_list')


    @method_decorator(permission_resource_required)
    def dispatch(self, request, *args, **kwargs):
        
        try:
            self.get_object()
        except Exception as e:
            messages.error(self.request, e)
            log.warning(force_text(e), extra=log_params(self.request))
            return HttpResponseRedirect(self.success_url)
        return super(PersonaDeleteView, self).dispatch(request, *args, **kwargs)


    def delete(self, request, *args, **kwargs):
        try:
            d = self.get_object()
            deps, msg = get_dep_objects(d)
            print(deps)
            if deps:
                messages.warning(self.request,  ('No se puede Eliminar %(name)s') % {
                    "name": capfirst(force_text(self.model._meta.verbose_name))
                    + ' "' + force_text(d) + '"'
                })
                raise Exception(msg)


            d.delete()
            msg = _(' %(name)s "%(obj)s" fue eliminado satisfactoriamente.') % {
                'name': capfirst(force_text(self.model._meta.verbose_name)),
                'obj': force_text(d)
            }
            if not d.id:
                messages.success(self.request, msg)
                log.warning(msg, extra=log_params(self.request))
        except Exception as e:
            messages.error(request, e)
            log.warning(force_text(e), extra=log_params(self.request))
        return HttpResponseRedirect(self.success_url)

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

class HitoriaBusquedaTemplateView(TemplateView):
    """Historia Template View.

    Clase usada para buscar el historial de una persona.
    """

    template_name = "historial/busqueda.html"

    def get(self, request, *args, **kwargs):
        try:
            codigo = request.GET['codigo']
            
            persona = Persona.objects.get(dni=codigo)


        except Exception as e:
            persona = ''

        try:
            historia = Historia.objects.get(persona__dni=codigo)

        except Exception as e:
            historia = ''

        context = {'persona': persona, 'historia': historia}


        return self.render_to_response(context)

# class Producto==============================================================================
class ProductoListView(ListView):
    model = Producto
    template_name = 'producto/producto_list.html'
    paginate_by = settings.PER_PAGE

    @method_decorator(permission_resource_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ProductoListView, self).dispatch(request, *args, **kwargs)

    def get_paginate_by(self, queryset):
        if 'all' in self.request.GET:
            return None
        return ListView.get_paginate_by(self, queryset)

    def get_queryset(self):
        self.o = empty(self.request, 'o', '-id')
        self.f = empty(self.request, 'f', 'codigo')
        self.q = empty(self.request, 'q', '')
        column_contains = u'%s__%s' % (self.f, 'contains')

        return self.model.objects.filter(**{column_contains: self.q}).order_by(self.o)


    def get_context_data(self, **kwargs):
        context = super(ProductoListView, self).get_context_data(**kwargs)
        context['opts'] = self.model._meta
        context['cmi'] = 'producto'
        context['title'] = _('Select %s to change') % capfirst(_('Producto'))

        context['o'] = self.o
        context['f'] = self.f
        context['q'] = self.q.replace('/', '-')

        return context


class ProductoCreateView(CreateView):
    model = Producto
    form_class = ProductoForm
    template_name = 'producto/producto_add.html'
    success_url = reverse_lazy('atencion:producto_list')

    @method_decorator(permission_resource_required )
    def dispatch(self, request, *args, **kwargs):
        return super(ProductoCreateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ProductoCreateView, self).get_context_data(**kwargs)
        context['opts'] = self.model._meta
        context['cmi'] = 'producto'
        context['title'] = ('Agregar %s') % ('Producto')
        return context


    def form_valid(self, form):
        self.object = form.save(commit=False)
        
        self.object.usuario = self.request.user

        
        msg = _(' %(name)s "%(obj)s" fue creado satisfactoriamente.') % {

apps/atencion/templates/producto/producto_add.html
{% extends "mod_hotel/base_mod_backend.html" %}

{% load i18n crispy_forms_tags %}
{% load l10n %}



{% block content_title %}
{{ opts.verbose_name|capfirst }} | <small>{{ title }}</small>
{% endblock content_title %}

{% block content %}
<div class="page-header">
        </h4><a href="#">Producto</a></h4>
    </div>
    <h2  >Crear Producto</h2> 

    <form action="" method="post">
    {{ form }}
    {% csrf_token %}
    <button type="submit" class="btn  btn-primary">Agregar</button>
    <a href="{% url 'atencion:persona_list' %}" class="btn btn-danger">Cancelar</a>
    </form>
{% endblock content %}

{% block extrajs %}
{{ block.super }}

<script type="text/javascript">

</script>
{% endblock extrajs %}

apps/atencion/templates/producto/producto_list.html
{% extends "mod_hotel/base_mod_backend.html" %}

{% block content %}

<script type="text/javascript">
$(function() {
    $('table').kgrid({
        form_data : ['{{f}}', '{{q}}'],
        form_to   : '{% url "atencion:producto_list" %}?f={{f}}&q={{q}}',
        order_attr: 'class=""',
        order_to  : '{% url "atencion:producto_list" %}?f={{f}}&q={{q}}',
    });
});
</script>
<div class="page-header">
        </h4><a href="#">Producto</a></h4>
    </div>
    <h2  >Lista de Productos</h2> 

    <div class="btn-toolbar btn-toolbar-top">
        <div class="row">
            <div class="btn-actions">
                <a href="{% url 'atencion:producto_add' %}" class="btn btn-primary text-bold" title="Agregar Producto">
                    <i class="fa fa-plus">
                    </i>
                    <span class="hidden-xs"> Agregar Producto
                    </span>
                </a>
            </div>
        </div>
    </div>

    <div class="container-overflow">
        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>#</th>
                    <th class="" data-search="codigo" data-order="codigo">Código</th>
                    <th class="" data-search="descripcion" data-order="descripcion">Descripción</th>
                    
                    <th class="btn-actions col-block text-center">Stock</th>
                
                    <th class="btn-actions col-block text-center">opcion</th>
                </tr>
            </thead>
            <tbody>
                {% for d in object_list %}
                <tr>
                    <td>
                        {% if is_paginated %}
                            {{ page_obj.start_index|add:forloop.counter0 }}
                        {% else %}
                            {{ forloop.counter }}
                        {% endif %}
                    </td>
                    <td>{{ d.codigo }}</td>
                    <td>{{ d.descripcion }}</td>
                    <td>{{ d.stock }}</td>
                   
                    <td class="text-center">
                        
                         <a href="{% url 'atencion:producto_update' d.id %}" class="btn btn-info btn-sm text-bold" title="Cambiar Producto" rel="tooltip"><i class="btn-icon-only fa fa-edit"></i></a>
                         <a href="{% url 'atencion:producto_delete' d.id %}" class="btn btn-danger btn-sm js-confirm text-bold" msg-title="Eliminar Producto?." msg="Estas seguro que quiere eliminar <br/> Recuerde que esta acción no se puede deshacer." title="Eliminar Producto" rel="tooltip"><i class="btn-icon-only fa fa-trash-o"></i></a>
                    </td>

                </tr>
                {% endfor %}
                
            </tbody>
        </table>
    </div>
   <div  class="row" >
    {% if is_paginated %}
    {% load paginator %}
    {% paginator %}
    {% else %}
    <div class="col-md-12" >
        <ul class="breadcrumbpag" >
            {{ object_list.count }}
            {% ifequal object_list.count 1 %}
                {{ opts.verbose_name|capfirst }}
            {% else %}{{ opts.verbose_name_plural|title }}
            {% endifequal %}
        </ul>
    </div>
    {% endif %}
</div>


{% endblock %}

{% block customjs %}
    <script>
     $('#delmodal').on('hidden.bs.modal', function () {
        $(location).attr('href', '{% url "atencion:producto_list" %}');
     });
    $('#updmodal').on('hidden.bs.modal', function () {
        $(location).attr('href', '{% url "atencion:producto_list" %}');
     });

    </script>
{% endblock %}